### PR TITLE
Change config

### PR DESCRIPTION
**Pull request by citizen428**
- Activated some cops that actually improve code quality
- Disable some of the more controversial ones (quotes, hash syntax etc)

There's probably plenty more that can be configured, but it's a start.

### CODE REVIEW

**Comment by citizen428** [comment]
Feedback anyone? :-)

**Comment by rhearnorth** [comment]
:+1: Merge them, We have to live with it anyway. right?

**Comment by consti** [comment]
+1

**Comment by ptmpn** [comment]
:+1:

**Pull request merged**
